language: rust
os:
  - linux
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install --force rustfmt-nightly
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo fmt -- --write-mode=diff; fi
  - cargo build
  - cargo test
