language: rust
os:
  - linux
rust:
  - stable
  - beta
cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - cargo install rustfmt --force || true
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo fmt -- --write-mode=diff; fi
  - cargo build
  - cargo test
