language: rust
os:
  - linux
rust:
  - stable
  - beta
cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup install nightly
  - cargo +nightly install --force rustfmt-nightly
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo +nightly fmt -- --write-mode=diff; fi
  - cargo build
  - cargo test
