[package]
name = "gb-rust"
version = "0.1.0"
authors = ["Aakash Patel <aakpat6@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.29.0"
env_logger = "0.4.3"
glium = "0.22.0"
log = "0.4.0"

[profile.release]
debug = true
