[package]
name = "gb-rust"
version = "0.1.0"
authors = ["Aakash Patel <aakpat6@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.29.0"
env_logger = "0.4.3"
log = "0.4.0"
anyhow = "1.0"
minifb = "0.19.3"
synth = "0.11.0"
portaudio = "0.7.0"

[profile.release]
debug = true
