name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v2.1.5
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v2.1.5
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - uses: Swatinem/rust-cache@v1
      - name: Install dependencies
        run: sudo apt-get install -y libxkbcommon-x11-dev libwayland-dev
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -v
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -v
